apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xe9rwfj0t-java-springboot
  janus-idp.io/tekton: xe9rwfj0t-java-springboot
  backstage.io/kubernetes-id: xe9rwfj0t-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xe9rwfj0t-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
