apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xe9rwfj0t-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:44bc66dbea146952d37aaaa04de52d5816e57896@sha256:13eeb4879bad3ca520f36c8fe4fc972bbfcec3157ea6e88c298f0757c848017c
          name: container-image
